server:
  port: 8080

spring:
  jpa:
    database: postgresql
    show-sql: true
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: true

  datasource:
    url: jdbc:postgresql://localhost:5432/lesson_seven
    username: grant
    password: 12341234

  flyway:
    locations: classpath:db/migration
    enabled: true

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.orm.jdbc.bind: TRACE
